name: "🐛 Bug Report"
description: Report a reproducible problem to help us fix it fast
labels: [bug]
assignees: []
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened? What did you expect?
      placeholder: A clear and concise description of the bug
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps To Reproduce
      description: Include prompt/seed/snapshot JSON if possible.
      placeholder: |
        1. Start server and open /demo
        2. Load model 'Tiny'
        3. Enter prompt '...'
        4. Press 'Generate'
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste any relevant logs or screenshots
      render: shell
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: OS, Browser, GPU/Driver, Python/PyTorch versions

