name: Add Issues/PRs to Project

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue or PR to project
        uses: actions/add-to-project@v0.6.0
        with:
          # TODO: Replace with your Project (v2) URL
          # e.g., https://github.com/users/annasba07/projects/1
          project-url: ${{ secrets.PROJECT_URL }}
          github-token: ${{ secrets.GH_TOKEN }}

